### ISSUE TITLE
Would it make sense to also support re-throw?

### ISSUE THREAD

**Issue by rbuckton** [michaelficarra/optional-catch-binding-proposal#1]
Given that this proposal allows you to elide the catch variable, would it be worth also having an expressionless `throw` to rethrow the caught exception without needing to refer to it by name?

```js
try {
  // ...
}
catch {
  // ...
  throw;
}
```

or...

```js
try {
  // ...
}
catch(e) {
  // ...
  throw; // equivalent to 'throw e;'
}
```

**Comment by michaelficarra** [comment]
I'd rather not. If you want to do that, you can name it. This proposal isn't about being terse, it's about not forcing unused bindings.
